import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import TopNav from './components/topNav'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
            <TopNav />
        {children}</body>
    </html>
  )
}
